{{ if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "git-apiserver.fullname" . }}
  labels:
    {{- include "git-apiserver.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "git-apiserver.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "git-apiserver.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{ end }}
