{{ if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "git-apiserver.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "git-apiserver.labels" . | nindent 4 }}
{{ end }}
